# If enabled, it will use the Minecraft vanilla rarities
use-default: true

rarities:
  - id: common
    items: [ ]
    display: "&a&lCOMMON"
  - id: uncommon
    items:
      - diamond_pickaxe
    display: "&e&lUNCOMMON"